version: '3'

services:
    web:
        build: .
        command: python -u flask_brevets.py
        ports:
            - "5000:5000"
        links:
            - db
    db:
        image: mongo:latest
